ENT.Type = "anim"
ENT.Base = "base_gmodentity"
ENT.RenderGroup = RENDERGROUP_BOTH
ENT.PrintName		= "Modern Refinary"
ENT.Spawnable = true
ENT.AdminOnly = true
ENT.Author			= "evil factory"
ENT.Contact			= "fredespy@outlook.com"
ENT.Category = "Evil_mining"
ENT.Instructions	= ""
