	surface.CreateFont( "FonteEntidade1", {
	font = "Roboto", 
	extended = false,
	size = 150,
	weight = 150,
	blursize = 0,
	scanlines = 0,
	antialias = true,
	underline = false,
	italic = false,
	strikeout = false,
	symbol = false,
	rotary = false,
	shadow = false,
	additive = false,
	outline = false,
} )

	surface.CreateFont( "FonteEntidade2", {
	font = "Roboto", 	extended = false,
	size = 40,
	weight = 150,
	blursize = 0,
	scanlines = 0,
	antialias = true,
	underline = false,
	italic = false,
	strikeout = false,
	symbol = false,
	rotary = false,
	shadow = false,
	additive = false,
	outline = false,
} )
